Greeter: Greeter.c
	gcc -ansi -static -fno-stack-protector -z execstack -g -no-pie -m32 Greeter.c -o Greeter
	gcc -ansi  -fno-stack-protector -z execstack -g -m32 test.c -o test;
clean:
	rm Greeter
	rm test
